# Create pod dotnet in yaml manifest file
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dotnetapp
  template:
    metadata:
      labels:
        app: dotnetapp
    spec:
      containers:
      - name: dotnetapp
        image: 381492032511.dkr.ecr.us-east-1.amazonaws.com/dotnetapp:v2
        ports:
        - containerPort: 8080
        env:
        - name: DbConnectionString
          valueFrom:
            secretKeyRef:
              name: dotnet-secret
              key: DbConnectionString
---
apiVersion: v1
kind: Service
metadata:
  name: dotnet-service
spec:
  selector:
    app: dotnetapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: v1
kind: Secret
metadata:
  name: dotnet-secret
type: Opaque
data:
  DbConnectionString: U2VydmVyPWNsb3VkbmF0aXZlc3YtZGV2LmNoODY0dXlzNmtsci51cy1lYXN0LTEucmRzLmFtYXpvbmF3cy5jb20sMTQzMztEYXRhYmFzZT1kYlRvZG87VXNlciBJZD1hZG1pbjtQYXNzd29yZD1DUzVFcUUoIUJxVjp4JGZ9NThkWXchSSp5e0dUO1RydXN0U2VydmVyQ2VydGlmaWNhdGU9VHJ1ZTsK
  